easy_admin:
    formats:
        date:     'd/m/Y'           # Format d'affichage des dates
        time:     'H:i:s'           # Format d'affichage des heures/minutes/secondes
        datetime: 'd/m/Y H:i:s'     # Format d'affichage des datetime
    site_name: 'Administration Générale'    # Nom du backoffice, marqué en haut à gauche de l'interface
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"           # Active le thème de bootstrap 4 pour l'apparence des formulaires
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"     # Active le thème de ckeditor pour les champs ckeditor
        brand_color: 'black'        # Couleur principale du backoffice (boutons, icônes, etc...)
        menu:       # Paramétrage du menu de gauche
            - { label: 'Revenir au site', route: 'main_home', icon: 'link'}     # Création d'un lien permettant de revenir sur le site sur l'accueil
            - User      # Affiche le menu principal pour l'entité "User" (on pourrait en mettre d'autres pour d'autres entités du site)
            - Activity
            - Comment
    entities:       # Paramétrage de la gestion des entités du site par easyadmin
        User:       # Paramétrage de l'entité User
            class: App\Entity\User      # Classe de l'entité User
            label: 'Utilisateurs'       # Nom d'affichage de l'entité User
            list:       # Paramétrage de l'onglet d'affichage des utilisateurs
                title: 'Liste des utilisateurs'     # Titre de l'onglet
                sort: ['id', 'ASC']     # Tri par défaut
                fields:     # Paramétrage des colonnes affichées ainsi que de leur type et leur titre
                    - {property: 'id', label: 'ID'}
                    - {property: 'email', type: 'email', label: 'Adresse Email'}
                    - {property: 'pseudonym', label: 'Pseudonyme'}
                    - {property: 'firstname', label: 'Prénom'}
                    - {property: 'lastname', label: 'Nom'}
                    - {property: 'is_verified', type: 'email', label: 'Email confirmé'}
            edit:   # Paramétrage de l'onglet de modification d'un utilisateur
                title: 'Modifier un utilisateur'    # Titre de l'onglet
                fields:     # Paramétrage des champs qui seront affichés dans le formulaire d'édition, ainsi que leur type et leur label
                    - {property: 'email', type: 'email', label: 'Adresse Email'}
                    - {property: 'pseudonym', label: 'Pseudonyme'}
                    - {property: 'firstname', label: 'Prénom'}
                    - {property: 'lastname', label: 'Nom'}
                    - {property: 'is_verified', type: 'email', label: 'Email confirmé'}
                    - {property: 'registrationToken', label: 'Token de registration'}
            new:    # Paramétrage de l'onglet d'ajout d'un utilisateur
                title: 'Créer un nouveau compte'    # Titre de l'onglet
                fields:     # Paramétrage des champs qui seront affichés dans le formulaire de création, ainsi que leur type et leur label
                    - {property: 'email', type: 'email', label: 'Adresse Email'}
                    - {property: 'password', type: 'password', label: 'Mot de passe'}
                    - {property: 'pseudonym', label: 'Pseudonyme'}
                    - {property: 'firstname', label: 'Prénom'}
                    - {property: 'lastname', label: 'Nom'}
                    - {property: 'is_verified', type: 'email', label: 'Email confirmé'}
                    - {property: 'registrationToken', label: 'Token de registration'}

        Activity:       # Paramétrage de l'entité Activity
            class: App\Entity\Activity      # Classe de l'entité Activity
            label: 'Les activités'       # Nom d'affichage de l'entité Activity
            list:       # Paramétrage de l'onglet d'affichage des activités
                title: 'Liste des utilisateurs'     # Titre de l'onglet
                sort: ['id', 'ASC']     # Tri par défaut
                fields:     # Paramétrage des colonnes affichées ainsi que de leur type et leur titre
                    - {property: 'id', label: 'ID'}
                    - {property: 'title', label: 'Titre'}
                    - {property: 'author', label: 'Auteur'}
                    - {property: 'comments', label: 'Commentaires'}
            edit:   # Paramétrage de l'onglet de modification des activités
                title: 'Modifier une activité'    # Titre de l'onglet
                fields:     # Paramétrage des champs qui seront affichés dans le formulaire d'édition, ainsi que leur type et leur label
                    - {property: 'title', label: 'Titre'}
                    - {property: 'description', type: 'fos_ckeditor', label: 'Contenu'}
                    - {property: 'author', label: 'Auteur'}
                    - {property: 'comments', label: 'Commentaires'}
            new:    # Paramétrage de l'onglet d'ajout des activités
                title: 'Créer une nouvelle activité'    # Titre de l'onglet
                fields:     # Paramétrage des champs qui seront affichés dans le formulaire de création, ainsi que leur type et leur label
                    - {property: 'title', label: 'Titre'}
                    - {property: 'description', type: 'fos_ckeditor', label: 'Contenu'}
                    - {property: 'author', label: 'Auteur'}

        Comment:       # Paramétrage de l'entité Comment
            class: App\Entity\Comment       # Classe de l'entité Comment
            label: 'Commentaires'          # Nom d'affichage de l'entité Comment
            list:        # Paramétrage de l'onglet d'affichage des commentaires
                title: 'Liste des Commentaires'        # Titre de l'onglet
                sort: ['publicationDate', 'DESC']    # Tri par défaut
                fields:
                    - {property: 'id', label: 'ID'}
                    - {property: 'author', label: 'Auteur'}
                    - {property: 'activity', label: 'Activity'}
            edit:     # Paramétrage de l'onglet de modification des commentaires
                title: 'Modifier un commentaire'    # Titre de l'onglet
                fields:     # Paramétrage des champs qui seront affichés dans le formulaire de création, ainsi que leur type et leur label
                    - {property: 'author', label: 'Auteur'}
                    - {property: 'activity', label: 'Activity'}
                    - {property: 'content', label: 'Contenu'}
            new:     # Paramétrage de l'onglet d'ajout des commentaires
                title: 'Créer un nouveau commentaire'    # Titre de l'onglet
                fields:     # Paramétrage des champs qui seront affichés dans le formulaire de création, ainsi que leur type et leur label
                    - {property: 'author', label: 'Auteur'}
                    - {property: 'activity', label: 'Activity'}
                    - {property: 'content', label: 'Contenu'}